### ISSUE TITLE
index.html引入node_modules样式

### ISSUE THREAD

**Issue by colorful-app** [ooboqoo/primeng-webpack2-starter#1]

**Comment by ooboqoo** [comment]
您忘了执行命令 `npm install` 吧？

**Comment by colorful-app** [comment]
不是你的项目，自己的项目，node_modules中的样式都是not found，
![qq 20170109171934](https://cloud.githubusercontent.com/assets/14008067/21761730/e1d814a6-d68f-11e6-9dc0-c53d9c5bb755.png)

**Comment by ooboqoo** [comment]
您看下 `node_modules\primeng\resources` 文件夹下是否存在 `primeng.min.css`， 我这边都有这文件的。
如果没找到，那您再安装一遍 primeng 试下 `npm install primeng`

**Comment by colorful-app** [comment]
primeng安装是正确的，node_modules中是存在的，只不过node_modules中的样式打不进去，可能是webpack配置的问题。

**Comment by colorful-app** [comment]
谢谢

**Comment by ooboqoo** [comment]
`<link rel="stylesheet" href="../node_modules/primeng/resources/themes/omega/theme.css">` 

前面两点是无效的，你无法读取根目录的父目录下其他内容，这是不允许的
